version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4200:80"
    depends_on:
      - proxy
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
